#!/usr/bin/env php
<?php

require_once __DIR__.'/../vendor/autoload.php';

use Wsdl2PhpGenerator\Console\Application;

define('APP_ROOT', __DIR__);

$application = new Application();
$application->run();